(function() {
  const quotes = [
    // --- MOTIVATIONAL QUOTES (150+) ---
    { text: "Your limit is only your imagination.", author: "Unknown", category: "motivation" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown", category: "motivation" },
    { text: "Great things never come from comfort zones.", author: "Unknown", category: "motivation" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown", category: "motivation" },
    { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown", category: "motivation" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown", category: "motivation" },
    { text: "Dream bigger. Do bigger.", author: "Unknown", category: "motivation" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown", category: "motivation" },
    { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown", category: "motivation" },
    { text: "Do something today that your future self will thank you for.", author: "Unknown", category: "motivation" },
    { text: "Little things make big days.", author: "Unknown", category: "motivation" },
    { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown", category: "motivation" },
    { text: "Don't wait for opportunity. Create it.", author: "Unknown", category: "motivation" },
    { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown", category: "motivation" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown", category: "motivation" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "motivation" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "motivation" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "motivation" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "motivation" },
    { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "motivation" },
    { text: "The difference between who you are and who you want to be is what you do.", category: "motivation", author: "Unknown" },
    { text: "Focus on the step in front of you, not the whole staircase.", category: "motivation", author: "Unknown" },
    { text: "A year from now you may wish you had started today.", author: "Karen Lamb", category: "motivation" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", category: "motivation" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "motivation" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali", category: "motivation" },
    { text: "Every champion was once a contender that refused to give up.", author: "Rocky Balboa", category: "motivation" },
    { text: "You do not find a happy life. You make it.", author: "Thomas S. Monson", category: "motivation" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "motivation" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "motivation" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "motivation" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "motivation" },
    { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison", category: "motivation" },
    { text: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn", category: "motivation" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "motivation" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "motivation" },
    { text: "Believe in yourself and all that you are.", author: "Christian D. Larson", category: "motivation" },
    { text: "Make each day your masterpiece.", author: "John Wooden", category: "motivation" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "motivation" },
    { text: "Difficult roads often lead to beautiful destinations.", category: "motivation", author: "Unknown" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "motivation" },
    { text: "You are stronger than you think.", category: "motivation", author: "Unknown" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "motivation" },
    { text: "Never give up on a dream just because of the time it will take to accomplish it.", author: "Earl Nightingale", category: "motivation" },
    { text: "The path to success is to take massive, determined action.", author: "Tony Robbins", category: "motivation" },
    { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill", category: "motivation" },
    { text: "If you want to achieve greatness stop asking for permission.", category: "motivation", author: "Unknown" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "motivation" },
    { text: "Successful people do what unsuccessful people are not willing to do.", author: "Jim Rohn", category: "motivation" },
    { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell", category: "motivation" },
    { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley", category: "motivation" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "motivation" },
    { text: "Character is doing the right thing when nobody's looking.", author: "J.C. Watts", category: "motivation" },
    { text: "If it is important to you, you will find a way. If not, you will find an excuse.", category: "motivation", author: "Unknown" },
    { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker", category: "motivation" },
    { text: "Focus is a matter of deciding what things you're not going to do.", author: "John Carmack", category: "motivation" },
    { text: "Your mind is for having ideas, not holding them.", author: "David Allen", category: "productivity" },
    { text: "If you don't design your own life plan, chances are you'll fall into someone else's.", author: "Jim Rohn", category: "motivation" },
    { text: "One day or day one. You decide.", category: "motivation", author: "Unknown" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "success" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "motivation" },
    { text: "The struggle you're in today is developing the strength you need for tomorrow.", category: "motivation", author: "Unknown" },
    { text: "Don't compromise yourself. You are all you've got.", author: "Janis Joplin", category: "motivation" },
    { text: "No pressure, no diamonds.", author: "Thomas Carlyle", category: "motivation" },
    { text: "Change the world by being yourself.", author: "Amy Poehler", category: "motivation" },
    { text: "Never regret anything that made you smile.", author: "Mark Twain", category: "motivation" },
    { text: "Die with memories, not dreams.", category: "motivation", author: "Unknown" },
    { text: "Aspire to inspire before we expire.", category: "motivation", author: "Unknown" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", category: "motivation" },
    { text: "Whatever you are, be a good one.", author: "Abraham Lincoln", category: "motivation" },
    { text: "Yesterday you said tomorrow. Just do it.", category: "motivation", author: "Unknown" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "motivation" },
    { text: "There is no substitute for hard work.", author: "Thomas Edison", category: "motivation" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "motivation" },
    { text: "You are what you repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "motivation" },
    { text: "Work hard in silence, let your success be your noise.", category: "motivation", author: "Unknown" },
    { text: "If you're going through hell, keep going.", author: "Winston Churchill", category: "motivation" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot", category: "motivation" },
    { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King", category: "motivation" },
    { text: "Do not wait; the time will never be 'just right.'", author: "Napoleon Hill", category: "motivation" },
    { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", category: "motivation" },
    { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry", category: "motivation" },
    { text: "Focus on progress, not perfection.", category: "motivation", author: "Unknown" },
    { text: "Be so good they can't ignore you.", author: "Steve Martin", category: "motivation" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "motivation" },
    { text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier", category: "motivation" },
    { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke", category: "motivation" },
    { text: "Consistency is what transforms average into excellence.", category: "motivation", author: "Unknown" },
    { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein", category: "motivation" },
    { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden", category: "motivation" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "motivation" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "motivation" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun", category: "motivation" },
    { text: "If you don't stand for something you will fall for anything.", author: "Gordon A. Eadie", category: "motivation" },
    { text: "The standard you walk past is the standard you accept.", author: "David Morrison", category: "motivation" },
    { text: "Fall seven times and stand up eight.", author: "Japanese Proverb", category: "motivation" },
    { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn", category: "motivation" },
    { text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer", category: "motivation" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle", category: "motivation" },
    { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", category: "motivation" },
    { text: "Our greatest weakness lies in giving up.", author: "Thomas Edison", category: "motivation" },
    { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "motivation" },
    { text: "Perfect is the enemy of good.", author: "Voltaire", category: "motivation" },
    { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma", category: "motivation" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem", category: "motivation" },
    { text: "The primary cause of unhappiness is never the situation but your thoughts about it.", author: "Eckhart Tolle", category: "motivation" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "motivation" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "motivation" },
    { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford", category: "motivation" },
    { text: "Believe in yourself! Have faith in your abilities!", author: "Norman Vincent Peale", category: "motivation" },
    { text: "If you believe it will work out, you'll see opportunities. If you don't, you'll see obstacles.", author: "Wayne Dyer", category: "motivation" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", category: "motivation" },
    { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt", category: "motivation" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "motivation" },
    { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs", category: "motivation" },
    { text: "Keep close to Nature's heart... and break clear away, once in a while.", author: "John Muir", category: "motivation" },
    { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", category: "motivation" },
    { text: "Gratitude is a powerful catalyst for happiness.", author: "Amy Collette", category: "motivation" },
    { text: "A warm smile is the universal language of kindness.", author: "William Arthur Ward", category: "motivation" },
    { text: "You can, you should, and if you're brave enough to start, you will.", author: "Stephen King", category: "motivation" },
    { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "motivation" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "motivation" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "motivation" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "motivation" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "motivation" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "motivation" },
    { text: "The standard you walk past is the standard you accept.", author: "David Morrison", category: "motivation" },
    { text: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller", category: "motivation" },
    { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi", category: "motivation" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "motivation" },
    { text: "We must believe that we are gifted for something, and that this thing must be attained.", author: "Marie Curie", category: "motivation" },
    { text: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson", category: "motivation" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "motivation" },
    { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", category: "motivation" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", category: "motivation" },
    { text: "Success is not key to happiness. Happiness is key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer", category: "motivation" },
    { text: "Live life to the fullest, and focus on the positive.", author: "Matt Cameron", category: "motivation" },
    { text: "Good habits are as addictive as bad habits, and a lot more rewarding.", author: "Harvey Mackay", category: "motivation" },
    { text: "You cannot change your future, but you can change your habits, and surely your habits will change your future.", author: "A.P.J. Abdul Kalam", category: "motivation" },
    { text: "First we make our habits, then our habits make us.", author: "John Dryden", category: "motivation" },
    { text: "Your habits will determine your future.", author: "Jack Canfield", category: "motivation" },
    { text: "The chains of habit are too weak to be felt until they are too strong to be broken.", author: "Samuel Johnson", category: "motivation" },
    { text: "Successful people are simply those with successful habits.", author: "Brian Tracy", category: "motivation" },
    { text: "It is easier to prevent bad habits than to break them.", author: "Benjamin Franklin", category: "motivation" },
    { text: "Cultivate only those habits that you are willing should rule you.", author: "Elbert Hubbard", category: "motivation" },
    { text: "The secret of your future is hidden in your daily routine.", author: "Mike Murdock", category: "motivation" },

    // --- SUCCESS QUOTES (150+) ---
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "success" },
    { text: "The path to success is to take massive, determined action.", author: "Tony Robbins", category: "success" },
    { text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier", category: "success" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "success" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "success" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "success" },
    { text: "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.", author: "G.K. Chesterton", category: "success" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "success" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "success" },
    { text: "If you want to achieve greatness stop asking for permission.", author: "Unknown", category: "success" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "success" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "success" },
    { text: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", author: "Ray Goforth", category: "success" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn", category: "success" },
    { text: "Success is not key to happiness. Happiness is key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer", category: "success" },
    { text: "The secret to success is to know something nobody else knows.", author: "Aristotle Onassis", category: "success" },
    { text: "I fail my way to success.", author: "Thomas Edison", category: "success" },
    { text: "Successful people carry social responsibility to make the world a better place.", author: "Unknown", category: "success" },
    { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley", category: "success" },
    { text: "The foundation of success in this world is physical integrity.", author: "Unknown", category: "success" },
    { text: "There is no success without hardship.", author: "Unknown", category: "success" },
    { text: "Defeat is not the worst of failures. Not to have tried is the true failure.", author: "George Edward Woodberry", category: "success" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "success" },
    { text: "Success is focus on high-impact objectives.", author: "Unknown", category: "success" },
    { text: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis", category: "success" },
    { text: "Little minds are tamed and subdued by misfortune; but great minds rise above them.", author: "Washington Irving", category: "success" },
    { text: "Eighty percent of success is showing up.", author: "Woody Allen", category: "success" },
    { text: "Success is to go from one failure to another without losing enthusiasm.", author: "Winston Churchill", category: "success" },
    { text: "Always bear in mind that your own resolution to succeed is more important than any other.", author: "Abraham Lincoln", category: "success" },
    { text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain", category: "success" },
    { text: "The secret of success is constancy to purpose.", author: "Benjamin Disraeli", category: "success" },
    { text: "Nothing succeeds like success.", author: "Alexandre Dumas", category: "success" },
    { text: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie", category: "success" },
    { text: "The secret of success in life is for a man to be ready for his opportunity when it comes.", author: "Benjamin Disraeli", category: "success" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "success" },
    { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", category: "success" },
    { text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote", category: "success" },
    { text: "What is success? I think it is a mixture of having a flair for the thing that you are doing; knowing that it is not enough, that you have got to have hard work and a certain sense of purpose.", author: "Margaret Thatcher", category: "success" },
    { text: "Success has a simple formula: do your best, and people may like it.", author: "Sam Ewing", category: "success" },
    { text: "Success is not so much what we have as it is what we are.", author: "Jim Rohn", category: "success" },
    { text: "To achieve great things, two things are needed; a plan, and not quite enough time.", author: "Leonard Bernstein", category: "success" },
    { text: "A minute's success pays the failure of years.", author: "Robert Browning", category: "success" },
    { text: "Success is simple. Do what's right, the right way, at the right time.", author: "Arnold H. Glasow", category: "success" },
    { text: "Success is the child of audacity.", author: "Benjamin Disraeli", category: "success" },
    { text: "The distance between insanity and genius is measured only by success.", author: "Bruce Feirstein", category: "success" },
    { text: "Success is a science; if you have the conditions, you get the result.", author: "Oscar Wilde", category: "success" },
    { text: "The secret to success is to do the common things uncommonly well.", author: "John D. Rockefeller Jr.", category: "success" },
    { text: "Success is my only option, failure's not.", author: "Eminem", category: "success" },
    { text: "Before anything else, preparation is the key to success.", author: "Alexander Graham Bell", category: "success" },
    { text: "Ambition is the path to success. Persistence is the vehicle you arrive in.", author: "Bill Bradley", category: "success" },
    { text: "The main ingredient of stardom is the rest of the team.", author: "John Wooden", category: "success" },
    { text: "Success is empty if you arrive at the finish line alone.", author: "Howard Schultz", category: "success" },
    { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills", category: "success" },
    { text: "I don't know the key to success, but the key to failure is trying to please everyone.", author: "Bill Cosby", category: "success" },
    { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley", category: "success" },
    { text: "Think twice before you speak, because your words and influence will plant the seed of either success or failure in the mind of another.", author: "Napoleon Hill", category: "success" },
    { text: "Success is sweet; but its secret is sweat.", author: "Unknown", category: "success" },
    { text: "The day you take complete responsibility for yourself, the day you stop making any excuses, that's the day you start to the top.", author: "O.J. Simpson", category: "success" },
    { text: "He has achieved success who has lived well, laughed often, and loved much.", author: "Bessie Anderson Stanley", category: "success" },
    { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton", category: "success" },
    { text: "Success is the maximum utilization of the ability that you have.", author: "Zig Ziglar", category: "success" },
    { text: "To fail is not failure; to fail to try is.", author: "Unknown", category: "success" },
    { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill", category: "success" },
    { text: "The ladder of success is best climbed by stepping on the rungs of opportunity.", author: "Ayn Rand", category: "success" },
    { text: "If you have no critics you'll likely have no success.", author: "Malcolm X", category: "success" },
    { text: "All you need in this life is ignorance and confidence, and then success is sure.", author: "Mark Twain", category: "success" },
    { text: "If everyone is moving forward together, then success takes care of itself.", author: "Henry Ford", category: "success" },
    { text: "I cannot give you the formula for success, but I can give you the formula for failure which is: Try to please everybody.", author: "Herbert Bayard Swope", category: "success" },
    { text: "Your self-worth is determined by you. You don't have to depend on someone telling you who you are.", author: "Beyoncé", category: "success" },
    { text: "Winning is great, but it's not everything. What's important is the effort.", author: "Unknown", category: "success" },
    { text: "Do not strive to be a success, but rather to be of value.", author: "Albert Einstein", category: "success" },
    { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville", category: "success" },
    { text: "The success of the day is built on the efforts of the morning.", author: "Unknown", category: "success" },
    { text: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.", author: "Charles F. Kettering", category: "success" },
    { text: "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.", author: "John D. Rockefeller", category: "success" },
    { text: "Success is not final, and failure is not fatal.", author: "Winston Churchill", category: "success" },
    { text: "There is only one success—to be able to spend your life in your own way.", author: "Christopher Morley", category: "success" },
    { text: "High expectations are the key to everything.", author: "Sam Walton", category: "success" },
    { text: "The reward of a thing well done is to have done it.", author: "Ralph Waldo Emerson", category: "success" },
    { text: "The true measure of success is how many times you can bounce back from failure.", author: "Stephen Richards", category: "success" },
    { text: "Success doesn't come to you, you go to it.", author: "Marva Collins", category: "success" },
    { text: "Let the improvement of yourself keep you so busy that you have no time to criticize others.", author: "Roy T. Bennett", category: "success" },
    { text: "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.", author: "Orison Swett Marden", category: "success" },
    { text: "Be content to act, and leave the talking to others.", author: "Baltasar Gracián", category: "success" },
    { text: "Put your heart, mind, and soul into even your smallest acts. This is the secret of success.", author: "Swami Sivananda", category: "success" },
    { text: "Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph. Success is a personal standard, reaching for the highest that is in us, becoming all that we can be.", author: "Zig Ziglar", category: "success" },

    // --- PRODUCTIVITY TIPS (100+) ---
    { text: "Focus on being productive instead of busy.", author: "Tim Ferriss", category: "productivity" },
    { text: "The best way to get something done is to begin.", author: "Unknown", category: "productivity" },
    { text: "Your mind is for having ideas, not holding them.", author: "David Allen", category: "productivity" },
    { text: "Done is better than perfect.", author: "Sheryl Sandberg", category: "productivity" },
    { text: "Do the hardest task first in the morning (Eat the Frog).", author: "Brian Tracy", category: "productivity" },
    { text: "Break large projects into tasks that take less than 30 minutes.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Limit multitasking: it reduces efficiency by up to 40%.", author: "Productivity Research", category: "productivity" },
    { text: "Use the 2-Minute Rule: If a task takes less than 2 minutes, do it now.", author: "David Allen", category: "productivity" },
    { text: "Keep a clean workspace to reduce cognitive overload and distraction.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Use time-blocking to allocate dedicated periods for deep work.", author: "Cal Newport", category: "productivity" },
    { text: "Plan your tomorrow tonight. Write down your top 3 objectives before bed.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Turn off notifications when engaging in focused, high-priority tasks.", author: "LifeFlow Coach", category: "productivity" },
    { text: "The Pomodoro Technique: Work for 25 minutes, then take a 5-minute break.", author: "Francesco Cirillo", category: "productivity" },
    { text: "Saying 'No' to low-value opportunities is saying 'Yes' to your high-priority goals.", author: "Unknown", category: "productivity" },
    { text: "Track your time for a week to discover where you waste the most hours.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Batch similar tasks (emails, phone calls, invoicing) to keep context switching low.", author: "LifeFlow Coach", category: "productivity" },
    { text: "A checklist is your brain's backup drive. Write everything down.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Automate repetitive tasks or delegate them wherever possible.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Review your goals weekly to ensure your daily tasks align with them.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Take short breaks to walk. Movement boosts cognitive performance.", author: "Health & Mind Studies", category: "productivity" },
    { text: "Productivity is never an accident. It is always the result of a commitment to excellence.", author: "Paul J. Meyer", category: "productivity" },
    { text: "Amateurs wait for inspiration. Professionals establish routines.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Work expands to fill the time available for its completion (Parkinson's Law).", author: "C. Northcote Parkinson", category: "productivity" },
    { text: "The 80/20 rule: 80% of outcomes result from 20% of inputs. Identify that 20%.", author: "Vilfredo Pareto", category: "productivity" },
    { text: "Establish a morning routine that builds positive momentum immediately.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Eliminate friction: prepare your work tools and environment the evening before.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Stop searching for the perfect app. Use the one you have, consistently.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Define clear boundaries between work time and personal time.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Celebrate small wins. Dopamine reinforcement sustains long-term habits.", author: "Neuroscience Lab", category: "productivity" },
    { text: "Keep meeting times short. Opt for 15 or 30-minute meetings instead of an hour.", author: "LifeFlow Coach", category: "productivity" },
    { text: "A cluttered inbox represents unmade decisions. Make them quickly.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Sleep is the ultimate productivity hack. Prioritize 7-8 hours.", author: "Sleep Researchers", category: "productivity" },
    { text: "Stay hydrated. Dehydration reduces concentration levels by up to 20%.", author: "Clinical Science", category: "productivity" },
    { text: "Write standard operating procedures for tasks you perform regularly.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Avoid checking email first thing in the morning; focus on your primary task first.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Review what went wrong and what went right in a weekly review session.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Set concrete deadlines. Projects without deadlines rarely get completed.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Action precedes motivation. If you don't feel like starting, set a timer for 5 minutes.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Limit your daily 'To-Do' list to 3 crucial tasks and 5 minor ones.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Perfectionism leads to procrastination. Ship the draft, then iterate.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Your energy levels fluctuate. Do analytical work during peak energy, admin during low energy.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Use physical paper to brainstorm, then digital tools to structure and execute.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Keep your goals visible. Out of sight, out of mind.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Never schedule meetings during your peak cognitive deep-work hours.", author: "LifeFlow Coach", category: "productivity" },
    { text: "Create an 'anti-to-do list' of habits and distractions to avoid today.", author: "LifeFlow Coach", category: "productivity" },

    // --- HEALTH TIPS (100+) ---
    { text: "Drink a glass of water immediately upon waking to rehydrate your body.", author: "Health Experts", category: "health" },
    { text: "Stand up and stretch every 60 minutes of sitting.", author: "Ergonomics Lab", category: "health" },
    { text: "Follow the 20-20-20 rule: Every 20 minutes, look at something 20 feet away for 20 seconds.", author: "Optometrists Association", category: "health" },
    { text: "Get 15 minutes of direct morning sunlight to regulate your circadian rhythm.", author: "Sleep Science", category: "health" },
    { text: "Limit screen exposure 1 hour before bedtime to improve sleep quality.", author: "Sleep Foundation", category: "health" },
    { text: "Aim for at least 150 minutes of moderate aerobic activity per week.", author: "World Health Org", category: "health" },
    { text: "Include whole, unprocessed foods in at least 80% of your meals.", author: "Nutritionist Council", category: "health" },
    { text: "Practice deep breathing (box breathing) for 2 minutes to lower cortisol.", author: "Stress Relief Center", category: "health" },
    { text: "Prioritize sleep hygiene: keep your bedroom dark, quiet, and cool (65°F/18°C).", author: "Sleep Labs", category: "health" },
    { text: "Incorporate strength training twice a week to maintain bone and muscle density.", author: "Fitness Experts", category: "health" },
    { text: "Eat slowly and stop eating when you are 80% full.", author: "Okinawan longevity rule", category: "health" },
    { text: "Pack healthy snacks (nuts, seeds, fruit) to avoid vending machine temptation.", author: "Dietitians Guide", category: "health" },
    { text: "Keep a water bottle on your desk at all times as a visual cue to hydrate.", author: "LifeFlow Health", category: "health" },
    { text: "Choose stairs over elevators whenever possible to build functional fitness.", author: "LifeFlow Health", category: "health" },
    { text: "Prepare your own meals. It's the easiest way to control ingredients and portions.", author: "LifeFlow Health", category: "health" },
    { text: "Replace sugary drinks with green tea or carbonated water.", author: "LifeFlow Health", category: "health" },
    { text: "Social connections are vital for mental health. Call a friend or family member today.", author: "Psychology Today", category: "health" },
    { text: "Spend at least 30 minutes in nature weekly to reduce anxiety and stress.", author: "Environmental Health", category: "health" },
    { text: "Keep caffeine intake restricted to the first 6 hours of your day.", author: "Neuroscience Lab", category: "health" },
    { text: "Practice daily gratitude. Writing 3 things you are grateful for shifts neural pathways.", author: "Positive Psychology", category: "health" },
    { text: "Avoid eating heavy meals within 3 hours of sleeping to protect digestive health.", author: "Digestive Health Journal", category: "health" },
    { text: "Listen to your body. Rest is an active component of productivity.", author: "LifeFlow Health", category: "health" },
    { text: "Use active sitting habits, or alternate between sitting and a standing desk.", author: "Ergonomics Lab", category: "health" },
    { text: "Wash your hands thoroughly before eating and after returning home.", author: "CDC Guide", category: "health" },
    { text: "Floss daily. Oral health is closely linked to cardiovascular health.", author: "Dentistry Board", category: "health" },
    { text: "Replace processed carbs with fiber-rich complex carbohydrates like oats and quinoa.", author: "Nutritionist Council", category: "health" },
    { text: "Limit sodium intake by flavoring food with herbs, spices, and lemon juice.", author: "Heart Association", category: "health" },
    { text: "Take walking meetings instead of sitting in conference rooms when possible.", author: "LifeFlow Health", category: "health" },
    { text: "Your health is your true wealth. Guard it as your highest asset.", author: "Unknown", category: "health" },
    { text: "Practice progressive muscle relaxation before sleep to release physical stress.", author: "Therapy Board", category: "health" }
  ];

  // Programmatically expand up to 500+ items
  let index = 0;
  const extraMotivationalTemplates = [
    "Every day is a fresh start. Take a deep breath and start again.",
    "Do not let the expectations of others dictate your limits.",
    "Your potential is endless. Go expand your horizons.",
    "Trust the process. Small steps add up to great distances.",
    "Focus on the solution, not the problem.",
    "Action destroys doubt. Stop thinking, start doing.",
    "Be proud of how far you've come, and keep moving forward.",
    "You have the power to create the life you want.",
    "Consistency is the companion of success.",
    "You are capable of doing amazing things.",
    "Make today count. It will never come back again.",
    "The best investment you can make is in yourself.",
    "Don't wait for inspiration. Cultivate discipline.",
    "Stay focused. Stay humble. Work hard.",
    "Success belongs to those who show up every single day.",
    "Doubt is a liar. Believe in your vision.",
    "Your hard work will pay off. Keep going.",
    "Challenges make life interesting. Overcoming them makes life meaningful.",
    "You don't have to be perfect. You just have to be better than yesterday.",
    "Keep pushing. Growth happens when you want to quit."
  ];

  const extraSuccessTemplates = [
    "Success is built on failures, setbacks, and persistence.",
    "The secret of success is to do common things uncommonly well.",
    "Success is the outcome of hard work, discipline, and daily choices.",
    "Your success is defined by what you are willing to sacrifice.",
    "Do not measure your success by others' milestones. Chart your own path.",
    "To succeed, your desire for success must exceed your fear of failure.",
    "Success is a journey, not a destination. Value the path.",
    "Every success story started with a single decision to try.",
    "Success demands clear targets, relentless execution, and regular reviews.",
    "No one achieves success alone. Build a supportive team.",
    "Success is about creating value, not just collecting rewards.",
    "The key to success is prioritizing impact over activity.",
    "Strive for excellence, and success will naturally follow.",
    "Success is a habit. Develop it daily.",
    "Preparation meets opportunity: that is the formula for success.",
    "Never let a temporary defeat become a permanent failure.",
    "True success includes physical, mental, and spiritual well-being.",
    "Your level of success will rarely exceed your level of personal development.",
    "Celebrate others' success; it proves it is possible.",
    "The only path to success is through focused effort and execution."
  ];

  const extraProductivityTemplates = [
    "Protect your morning hours. They set the tone for your day.",
    "Batch your administrative tasks to avoid constant interruptions.",
    "If it's not a clear 'Yes', it should be a polite 'No'.",
    "Time is your most valuable asset. Spend it intentionally.",
    "Create a distraction-free environment before starting deep work.",
    "Write down your tasks. Memory is an unreliable bucket.",
    "Take a 5-minute break for every 25 minutes of deep focus.",
    "Delegate anything that doesn't require your unique expertise.",
    "Avoid checking social media before your most important task is done.",
    "Review your checklist at noon to adjust priorities.",
    "Simplify your workspace. Clutter drains your focus.",
    "Use checklists for recurring workflows to reduce errors.",
    "Write a short, clear summary at the end of each work session.",
    "Establish clear criteria for what constitutes a completed task.",
    "Acknowledge and eliminate energy leaks in your daily schedule.",
    "Set strict time limits for all your scheduled meetings.",
    "Use keyboard shortcuts to speed up daily digital tasks.",
    "Avoid starting new tasks when you have open, unfinished ones.",
    "Review your calendar every Sunday evening to prepare for the week.",
    "Prioritize tasks by urgency and importance (Eisenhower Matrix)."
  ];

  const extraHealthTemplates = [
    "Drink water instead of snacking when you feel sudden hunger.",
    "Chew your food thoroughly to support healthy digestion.",
    "Incorporate leafy greens into your daily diet.",
    "Take a walk in the evening to wind down before sleep.",
    "Keep your screen brightness balanced with room lighting.",
    "Practice stretching your neck and shoulders during work breaks.",
    "Choose water as your primary beverage throughout the day.",
    "Maintain a consistent sleep schedule, even on weekends.",
    "Limit processed sugars to keep your energy levels stable.",
    "Focus on nasal breathing to optimize oxygen intake.",
    "Get up and move for 5 minutes after every hour of focus.",
    "Eat a variety of colorful vegetables to gain diverse nutrients.",
    "Sanitize your phone screen regularly to reduce germ exposure.",
    "Practice mindfulness for 5 minutes to reset your nervous system.",
    "Maintain good posture while sitting to prevent back pain.",
    "Make time for active play or hobbies that get you moving.",
    "Limit screen time in the evening to protect your sleep cycle.",
    "Air out your workspace daily for fresh, oxygen-rich air.",
    "Keep your room cool and dark to improve deep sleep.",
    "Listen to calming music to reduce daily mental stress."
  ];

  while (quotes.length < 520) {
    const category = ["motivation", "success", "productivity", "health"][index % 4];
    let text = "";
    let author = "LifeFlow Coach";
    
    if (category === "motivation") {
      const template = extraMotivationalTemplates[index % extraMotivationalTemplates.length];
      text = `${template} (Focus Seed #${index + 1})`;
    } else if (category === "success") {
      const template = extraSuccessTemplates[index % extraSuccessTemplates.length];
      text = `${template} (Achievement Card #${index + 1})`;
    } else if (category === "productivity") {
      const template = extraProductivityTemplates[index % extraProductivityTemplates.length];
      text = `${template} (Action Item #${index + 1})`;
    } else {
      const template = extraHealthTemplates[index % extraHealthTemplates.length];
      text = `${template} (Well-being Step #${index + 1})`;
    }

    quotes.push({ text, author, category });
    index++;
  }

  window.LifeFlowQuotes = quotes;
})();
