name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Create Flutter Template Project
        run: |
          flutter create --org com.lifeflow --project-name lifeflow_app --platforms=android tmp_app

      - name: Overlay WebView code
        run: |
          cp lifeflow_mobile_wrapper/pubspec.yaml tmp_app/pubspec.yaml
          cp lifeflow_mobile_wrapper/lib/main.dart tmp_app/lib/main.dart

      - name: Build Android APK
        run: |
          cd tmp_app
          flutter pub get
          flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: lifeflow-apk
          path: tmp_app/build/app/outputs/flutter-apk/app-release.apk
